# Generated by Django 5.1.15 on 2026-04-02 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('OVERDUE', 'Overdue'), ('REMINDER', 'Reminder'), ('DIGEST', 'Digest')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('borrow_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='borrowing.borrowrecord')),
            ],
            options={
                'verbose_name': 'notification log',
                'verbose_name_plural': 'notification logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
