# Generated by Django 5.1.15 on 2026-04-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label_width_mm', models.FloatField()),
                ('label_height_mm', models.FloatField()),
                ('h_pitch_mm', models.FloatField(help_text='Horizontal distance from label start to next label start')),
                ('v_pitch_mm', models.FloatField(help_text='Vertical distance from label start to next label start')),
                ('left_margin_mm', models.FloatField()),
                ('top_margin_mm', models.FloatField()),
                ('rows', models.PositiveIntegerField()),
                ('columns', models.PositiveIntegerField()),
                ('offset_x_mm', models.FloatField(default=0)),
                ('offset_y_mm', models.FloatField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'sticker template',
                'verbose_name_plural': 'sticker templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
