# Generated by Django 5.1.15 on 2026-04-02 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_from', models.DateTimeField()),
                ('borrowed_until', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='assets.asset')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to='customers.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrow_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'borrow record',
                'verbose_name_plural': 'borrow records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_borrow_status'), models.Index(fields=['status', 'borrowed_until'], name='idx_borrow_overdue'), models.Index(fields=['asset', '-created_at'], name='idx_borrow_asset_history')],
            },
        ),
    ]
