# Generated by Django 5.1.15 on 2026-04-02 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('ASSET', 'Asset'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('DATE', 'Date'), ('STRING', 'String'), ('NUMBER', 'Number'), ('DECIMAL', 'Decimal'), ('SINGLE_SELECT', 'Single Select'), ('MULTI_SELECT', 'Multi Select')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'custom field definition',
                'verbose_name_plural': 'custom field definitions',
                'ordering': ['entity_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.JSONField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_fields.customfielddefinition')),
            ],
            options={
                'verbose_name': 'custom field value',
                'verbose_name_plural': 'custom field values',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='custom_fiel_content_a0fece_idx')],
            },
        ),
    ]
