# Generated by Django 5.1.15 on 2026-04-03 08:33

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_superuser_role_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
