# Generated by Django 5.1.15 on 2026-04-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appearance_bg_color',
            field=models.CharField(blank=True, default='', help_text='Hex color for content background, e.g. #f5f5f5', max_length=9),
        ),
        migrations.AddField(
            model_name='user',
            name='appearance_bg_image',
            field=models.ImageField(blank=True, default='', help_text='Custom background image for the content area.', upload_to='user_backgrounds/'),
        ),
        migrations.AddField(
            model_name='user',
            name='appearance_font_color',
            field=models.CharField(blank=True, default='', help_text='Hex color for content text, e.g. #1a1a1a', max_length=9),
        ),
    ]
